sudo: required
services:
  - docker

before_install:
  - docker build -t syedrakib/udemy-k8s-complex-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run syedrakib/udemy-k8s-complex-client-test npm test -- --coverage

after_success:
  - docker build -t syedrakib/udemy-k8s-complex-client ./client
  - docker build -t syedrakib/udemy-k8s-complex-nginx ./nginx
  - docker build -t syedrakib/udemy-k8s-complex-server ./server
  - docker build -t syedrakib/udemy-k8s-complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push syedrakib/udemy-k8s-complex-client
  - docker push syedrakib/udemy-k8s-complex-nginx
  - docker push syedrakib/udemy-k8s-complex-server
  - docker push syedrakib/udemy-k8s-complex-worker

# deploy:
#   edge: true # pre-emptive setting to make sure latest (experimental) travis deployment scheme is used
#   provider: elasticbeanstalk
#   region: ap-southeast-1
#   app: udemy-k8s-complex
#   env: UdemyK8sComplex-env
#   bucket_name: elasticbeanstalk-ap-southeast-1-623822791400
#   bucket_path: udemy-k8s-complex
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
